config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :categories
  resources :articles

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
  validates :category_id, presence: true

  belongs_to :category
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :articles

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_categories
    
  def index
    @title = "Listagem de Artigos"
    @articles = Article.all
  end

  def show
    begin
      @article = Article.find(params[:id])
    rescue
      redirect_to articles_path
    end
  end

  def edit
    begin
      @article = Article.find(params[:id])
    rescue
      redirect_to articles_path
    end
  end

  def update
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    redirect_to articles_path, status: :see_other
  end

  private
    def article_params
      params.require(:article).permit(:title, :body, :category_id)
    end

    def set_categories
      @categories = Category.all.order(:name)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
      @title = "Listagem de Categorias"
      @categories = Category.all
    end  

    def show
    begin
        @category = Category.find(params[:id])
    rescue
        redirect_to categories_path
    end
    end
    
    def edit
    begin
        @category = Category.find(params[:id])
    rescue
        redirect_to categories_path
    end
    end

    def update
    @category = Category.find(params[:id])

    if @category.update(category_params)
        redirect_to @category
    else
        render :edit, status: :unprocessable_entity
    end
    end

    def new
        @category = Category.new
    end 

    def create
    @category = Category.new(category_params)

    if @category.save
        redirect_to @category
    else
        render :new, status: :unprocessable_entity
    end
    end  
    
    def destroy
        @category = Category.find(params[:id])
        @category.destroy
    
        redirect_to categories_path, status: :see_other
    end    
    
    private
    def category_params
      params.require(:category).permit(:name)
    end    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% article.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
    <% article.errors.full_messages_for(:body).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.select :category_id, options_for_select(@categories.collect { |cat| [cat.name, cat.id]})%>
  </div>  

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h2 class="pb-3 mb-4 mt-4 border-bottom">
  <%= @title %>
  <%= link_to "Criar Novo Artigo" , new_article_path, class: 'btn btn-success float-end' %>
</h2>

<p class="text-end">

</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Categoria</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.id %></td>
        <td><%= article.title %></td>
        <td><%= article.category.name %></td>
        <td><%= article.created_at %></td>
        <td>
          <a href="<%= article_path(article.id) %>" class="btn btn-primary">
            Show
          </a>

          <a href="<%= edit_article_path(article.id) %>" class="btn btn-warning">
            Edit
          </a>

          <%= link_to "Excluir", article_path(article), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Vai dar merda, tem certeza?"
                  }, class: "btn btn-danger" %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/articles/new.html.erb
<%= render "form", article: @article %>

app/views/articles/show.html.erb
<dl>
  <dt>ID</dt>
  <dd><%= @article.id %>

  <dt>Title</dt>
  <dd><%= @article.title %>

  <dt>Body</dt>
  <dd><%= @article.body.html_safe %>

  <dt>Categoria</dt>
  <dd><%= @article.category.name %>

  <dt>Created At</dt>
  <dd><%= @article.created_at %>

  <dt>Updated At</dt>
  <dd><%= @article.updated_at %>
</dl>

app/views/categories/_form.html.erb
<%= form_with model: category do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% category.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<%= render "form", category: @category %>

app/views/categories/index.html.erb
<h2 class="pb-3 mb-4 mt-4 border-bottom">
  <%= @title %>
  <%= link_to "Criar Nova Categoria" , new_category_path, class: 'btn btn-success float-end' %>
</h2>

<p class="text-end">

</p>

<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Nome</th>
      <th>Created At</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.id %></td>
        <td><%= category.name %></td>
        <td><%= category.created_at %></td>
        <td>
          <a href="<%= category_path(category.id) %>" class="btn btn-primary">
            Show
          </a>

          <a href="<%= edit_category_path(category.id) %>" class="btn btn-warning">
            Edit
          </a>

          <%= link_to "Excluir", category_path(category), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Vai dar merda, tem certeza?"
                  }, class: "btn btn-danger" %>

        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/categories/new.html.erb
<%= render "form", category: @category %>

app/views/categories/show.html.erb
<dl>
  <dt>ID</dt>
  <dd><%= @category.id %>

  <dt>Nome</dt>
  <dd><%= @category.name %>

  <dt>Created At</dt>
  <dd><%= @category.created_at %>

  <dt>Updated At</dt>
  <dd><%= @category.updated_at %>
</dl>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApplication</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">First App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= articles_path %>">Articles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= categories_path %>">Categories</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <%= yield %>
        </div>
      </div>
    </div>    
  </body>
</html>